const PRODUCTS = [
  {
    id: 'm1',
    name: 'Chronos Steel',
    category: 'men',
    price: 249.99,
    image: 'images/media__1781799606973.jpg',
    description: 'Classic stainless steel chronograph with sapphire crystal and 100m water resistance.',
    brand: 'TimeForge',
    rating: 4.8,
  },
  {
    id: 'm2',
    name: 'Midnight Diver',
    category: 'men',
    price: 399.99,
    image: 'images/media__1781799611622.jpg',
    description: 'Professional dive watch with ceramic bezel and luminous markers for deep-sea clarity.',
    brand: 'AquaLine',
    rating: 4.9,
  },
  {
    id: 'm3',
    name: 'Heritage Leather',
    category: 'men',
    price: 179.99,
    image: 'images/media__1781799616188.jpg',
    description: 'Vintage-inspired automatic with genuine Italian leather strap and exhibition caseback.',
    brand: 'TimeForge',
    rating: 4.6,
  },
  {
    id: 'm4',
    name: 'Pilot Aviator',
    category: 'men',
    price: 329.99,
    image: 'images/media__1781799619561.jpg',
    description: 'Large-format pilot watch with dual timezone and anti-reflective coated dial.',
    brand: 'SkyMark',
    rating: 4.7,
  },
  {
    id: 'm5',
    name: 'Carbon Sport',
    category: 'men',
    price: 459.99,
    image: 'images/media__1781799630332.jpg',
    description: 'Lightweight carbon fiber case with GPS sync and heart-rate compatible smart features.',
    brand: 'PulseX',
    rating: 4.5,
  },
  {
    id: 'm6',
    name: 'Executive Gold',
    category: 'men',
    price: 899.99,
    image: 'images/media__1781799199950.jpg',
    description: '18K gold-plated dress watch with Swiss movement and alligator leather band.',
    brand: 'LuxeTime',
    rating: 4.9,
  },
  {
    id: 'w1',
    name: 'Rose Petal',
    category: 'women',
    price: 219.99,
    image: 'images/media__1781799203488.jpg',
    description: 'Elegant rose gold case with mother-of-pearl dial and diamond hour markers.',
    brand: 'LuxeTime',
    rating: 4.8,
  },
  {
    id: 'w2',
    name: 'Pearl Classic',
    category: 'women',
    price: 189.99,
    image: 'images/media__1781799217681.jpg',
    description: 'Minimalist pearl white dial with slim mesh bracelet for everyday sophistication.',
    brand: 'TimeForge',
    rating: 4.7,
  },
  {
    id: 'w3',
    name: 'Blossom Mini',
    category: 'women',
    price: 159.99,
    image: 'images/media__1781799220689.jpg',
    description: 'Petite 28mm case with floral engraved bezel and soft pink leather strap.',
    brand: 'Bloom & Co',
    rating: 4.6,
  },
  {
    id: 'w4',
    name: 'Crystal Edge',
    category: 'women',
    price: 349.99,
    image: 'images/media__1781799223713.jpg',
    description: 'Art-deco inspired design with crystal-set lugs and Swiss quartz precision.',
    brand: 'LuxeTime',
    rating: 4.9,
  },
  {
    id: 'w5',
    name: 'Ocean Breeze',
    category: 'women',
    price: 279.99,
    image: 'images/media__1781799606973.jpg',
    description: 'Turquoise ceramic bezel with silver sunburst dial — perfect for coastal adventures.',
    brand: 'AquaLine',
    rating: 4.5,
  },
  {
    id: 'w6',
    name: 'Velvet Night',
    category: 'women',
    price: 429.99,
    image: 'images/media__1781799611622.jpg',
    description: 'Midnight blue sunray dial with velvet finish strap and moonphase complication.',
    brand: 'Bloom & Co',
    rating: 4.8,
  },
  {
    id: 'm7',
    name: 'Modern Spectrum',
    category: 'men',
    price: 199.99,
    image: 'images/media__1781799199950.jpg',
    description: 'A modern colorful dial watch for the modern aesthetic.',
    brand: 'TimeForge',
    rating: 4.6,
  },
  {
    id: 'w7',
    name: 'Rose Gold Diamond',
    category: 'women',
    price: 349.99,
    image: 'images/media__1781799203488.jpg',
    description: 'An elegant rose gold watch with diamond bezel.',
    brand: 'LuxeTime',
    rating: 4.9,
  },
  {
    id: 'm8',
    name: 'Silver Chrono',
    category: 'men',
    price: 499.99,
    image: 'images/media__1781799217681.jpg',
    description: 'A professional and stylish silver chronograph.',
    brand: 'SkyMark',
    rating: 4.8,
  },
  {
    id: 'm9',
    name: 'Classic Moonphase',
    category: 'men',
    price: 899.99,
    image: 'images/media__1781799220689.jpg',
    description: 'A complex mechanical watch with a moon phase complication.',
    brand: 'LuxeTime',
    rating: 4.9,
  },
  {
    id: 'w8',
    name: 'Elegant Trio',
    category: 'women',
    price: 299.99,
    image: 'images/media__1781799223713.jpg',
    description: 'A stunning set of elegant women\'s watches.',
    brand: 'Bloom & Co',
    rating: 4.7,
  },
  {
    id: 'm10',
    name: 'Apple Watch Hermès',
    category: 'smart',
    price: 699.99,
    image: 'images/watch_apple_hermes.jpg',
    description: 'Premium Apple Watch Hermès edition with genuine dark leather strap and stainless steel case — the perfect blend of tech and luxury fashion.',
    brand: 'Apple',
    rating: 4.9,
  },
  {
    id: 'm11',
    name: 'Hublot Spirit Skeleton',
    category: 'men',
    price: 1299.99,
    image: 'images/watch_hublot_skeleton.jpg',
    description: 'Bold skeleton chronograph with black ceramic case and striking blue rubber strap — a masterpiece of avant-garde horology.',
    brand: 'Hublot',
    rating: 4.8,
  },
  {
    id: 'm12',
    name: '24H Minimal One-Hand',
    category: 'men',
    price: 349.99,
    image: 'images/watch_24h_minimal.jpg',
    description: 'Unique 24-hour single-hand minimalist watch with a clean white dial, blue needle and black leather strap for the modern timekeeper.',
    brand: 'TimeForge',
    rating: 4.6,
  },
  {
    id: 'm13',
    name: 'MeisterSinger Classic',
    category: 'men',
    price: 899.99,
    image: 'images/watch_meistersinger.jpg',
    description: 'Iconic single-hand automatic with a warm cream dial and premium brown alligator leather strap — refined German watchmaking heritage.',
    brand: 'MeisterSinger',
    rating: 4.9,
  },
  {
    id: 'm14',
    name: 'Triple Subdial Sport',
    category: 'men',
    price: 199.99,
    image: 'images/watch_silver_sport.jpg',
    description: 'Bold silver stainless steel sport watch with three functional subdials and a black dial — powerhouse precision for the active man.',
    brand: 'PulseX',
    rating: 4.7,
  }
];

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id);
}

function getProductsByCategory(category) {
  return PRODUCTS.filter((p) => p.category === category);
}

function formatPrice(price) {
  return 'PKR ' + (price * 280).toLocaleString();
}

function renderStars(rating) {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5;
  let stars = '';
  for (let i = 0; i < full; i++) stars += '★';
  if (half) stars += '½';
  return stars;
}
